### ISSUE TITLE
Always get an error

### ISSUE THREAD

**Issue by sunilrx** [feross/webtorrent-hybrid#42]
Hi i am new to webtorrent-hybrid,  so if i had done something wrong and please correct me.
I have installed  "npm install webtorrent-hybrid -g".
After if i type in terminal
webtorrent-hybrid $MAGNETURL
or
webtorrent-hybrid --help

i get the following error.
/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/electron-webrtc/src/RTCPeerConnection.js:10
  daemon.eval('window.conns = {}', (err) => {
                                          ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/electron-webrtc/index.js:11:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/webtorrent-hybrid/lib/global.js:2:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

Is there anything wrong in CLI installation ? Help apprciated.

**Comment by DiegoRBaquero** [comment]
Please update your node version. Arrow functions aren't supported by your current version.

**Comment by feross** [comment]
Yes, what @DiegoRBaquero said. I also added an `engines` field to `package.json` so there will be a warning on install when the version of node is too old.

**Comment by sunilrx** [comment]
Thank You...
