### ISSUE TITLE
error on  appendTo

### ISSUE THREAD

**Issue by jbelda** [feross/webtorrent-hybrid#52]
Hi!
I always get the same error when use the file method appendTo
this is the error

TypeError: Cannot read property 'appendChild' of null
    at createElem (.../webtorrent-hybrid/node_modules/webtorrent/node_modules/render-media/index.js:129:13)
    at createMedia (.../webtorrent-hybrid/node_modules/webtorrent/node_modules/render-media/index.js:120:16)
    at getElem (.../webtorrent-hybrid/node_modules/webtorrent/node_modules/render-media/index.js:115:60)
    at prepareElem (.../webtorrent-hybrid/node_modules/webtorrent/node_modules/render-media/index.js:235:16)
    at useVideostream (.../webtorrent-hybrid/node_modules/webtorrent/node_modules/render-media/index.js:171:7)
    at renderMediaSource (.../webtorrent-hybrid/node_modules/webtorrent/node_modules/render-media/index.js:161:9)
    at renderMedia (.../webtorrent-hybrid/node_modules/webtorrent/node_modules/render-media/index.js:145:5)
    at Object.append (.../webtorrent-hybrid/node_modules/webtorrent/node_modules/render-media/index.js:112:3)
    at File.appendTo (.../webtorrent-hybrid/node_modules/webtorrent/lib/file.js:90:10)

**Comment by feross** [comment]
It looks like you're not passing in a valid DOM node to `appendTo`.
