### ISSUE TITLE
Cannot add multiple torrents (Error: write EPIPE)

### ISSUE THREAD

**Issue by John-p0pe** [feross/webtorrent-hybrid#53]
node version : node 6.7.0 & 7.1.0
webtorrent-hybrid version : 1.0.5
os : debian jessie arm

Getting the following error when trying to add multiple torrent files.

```
xvfb-run node index.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1036:11)
    at WriteWrap.afterWrite (net.js:794:14)
```

code to reproduce

```
var WebTorrent = require('webtorrent-hybrid');
var client = new WebTorrent({
  maxConns: 200,        // Max number of connections per torrent (default=55)
  webSeeds: false        // Enable BEP19 web seeds (default=true)
})

var torrentId = 'http://cdimage.debian.org/debian-cd/8.6.0/arm64/bt-dvd/debian-8.6.0-arm64-DVD-1.iso.torrent'
var torrentId2 = 'http://cdimage.debian.org/debian-cd/8.6.0/multi-arch/bt-dvd/debian-8.6.0-i386-amd64-source-DVD-1.iso.torrent'
var torrentId3 = 'https://webtorrent.io/torrents/sintel.torrent'

client.add(torrentId, {path: "/mnt/test/"}, function (torrent) {
});
client.add(torrentId2, {path: "/mnt/test/"}, function (torrent) {
});
client.add(torrentId3, {path: "/mnt/test/"}, function (torrent) {
});
```

**Comment by feross** [comment]
I believe you shouldn't need to run your own copy of `xvfb`. Can you try again without `xvfb-run`?
