### ISSUE TITLE
after successful installation, running webtorrent-hybrid throws error

### ISSUE THREAD

**Issue by patriotyk** [feross/webtorrent-hybrid#62]
I have installed it with command `sudo npm install webtorrent-hybrid -g`

```
(xenial)patriotyk@localhost:~$ webtorrent-hybrid --help
/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/simple-websocket/node_modules/ws/lib/PerMessageDeflate.js:8
const TRAILER = Buffer.from([0x00, 0x00, 0xff, 0xff]);
                       ^

TypeError: this is not a typed array.
    at Function.from (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/simple-websocket/node_modules/ws/lib/PerMessageDeflate.js:8:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/webtorrent-hybrid/node_modules/simple-websocket/node_modules/ws/lib/WebSocket.js:16:27)
    at Module._compile (module.js:410:26)
```

**Comment by feross** [comment]
Can you try reinstalling one more time? This may have been a transient error in a dependency that has since been resolved. I get no such error with a fresh install.

Also, what OS, OS version, Node.js version, and npm version are you using?

**Comment by JacquesLG** [comment]
Hi I got exactly the same error. 
I used apt-get install nodejs and it installed version 4.5.103.35
I followed the "install with PPA" from DO and it works now https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-16-04#how-to-install-using-a-ppa

**Comment by DiegoRBaquero** [comment]
Seems you need NodeJS 6+: http://stackoverflow.com/a/36924697/4503431

**Comment by patriotyk** [comment]
Thank You, with new nodejs it works now. I suppose it it would be good idea to add in readme that it requires version of nodejs 6.0 and above.

**Comment by lpinca** [comment]
`Buffer.from()` has been backported and it is available in Node.js 4.5.0 or greater.

**Comment by Guisch** [comment]
Got the same problem 3 days ago (https://github.com/feross/simple-websocket/issues/15)
